<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{	
	public function getMyFriendsInTheList($id)
	{
		$queryBuilder=$this->createQueryBuilder('m');
		$queryBuilder      ->select('u')
				           ->from('UserBundle:User','u')				           
				           ->where('u.friendsWithMe = :id')
						   ->orderBy('u.name', 'ASC')
						   ->setParameter('id', $id);
		return $queryBuilder;
	}
}
 