user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

user_friend_list:
    path: user/friend/listByUser
    defaults: { _controller: UserBundle:Friend:list}

user_friend_editFriend:
    path: user/friend/editFriend/{id}
    defaults: { _controller: UserBundle:Friend:editFriend}
    requirements:
        id: "[0-9]+"

user_friend_show:
    path: user/friend/show/{id}
    defaults: { _controller: UserBundle:Friend:show}
    requirements:
        id: "[0-9]+"

user_friend_delete:
    path: user/friend/delete
    defaults: { _controller: UserBundle:Friend:delete}
    
fos_user_security_login:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_show:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

fos_user_registration_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile
